language: objective-c
branches:
  only:
    - master
cache:
  directories:
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
jobs:
  include:
  - stage: "Tests"
    osx_image: xcode10.2
    script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=10.3.1,name=iPhone SE'
    name: "iPhone SE (iOS 10.3)"
